---

- name: creating directory and file
  hosts:  root@9.30.194.94
 # hosts: 127.0.0.1
#  connection: local
  tasks:
    - name: Ansible create directory
      file:
        path: /Users/purush/Documents/Ansible
        state: directory
    - name: create file
      file:
        path: /Users/purush/Documents/Ansible/empty.txt
        state: touch
