---
- name: contentfile
  hosts: root@9.30.194.94
  tasks:
  - name: installing gedit
    command: sudo apt-get install gedit
  - name: Install nginx
    command: sudo apt-get install nginx
  - name: installing sublime
    shell:  |
      sudo add-apt-repository ppa:webupd8team/sublime-text-3
      sudo apt-get update
      sudo apt-get install sublime-text-installer
